/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.clm;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class EnterpriseContractApiTests {@Autowired MockMvc mvc;String token;@BeforeEach void login()throws Exception{String s=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\"planner\",\"password\":\"Demo@2026\"}")).andReturn().getResponse().getContentAsString();var m=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)").matcher(s);Assertions.assertTrue(m.find());token=m.group(1);}
 @Test void contractVersionAmendmentAndObligationAreTraceable() throws Exception {var result=mvc.perform(post("/api/admin/contracts").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("""
 {"contractNo":"ENT-CLM-001","title":"年度技术服务合同","counterparty":"示例客户","organizationCode":"ZH-SH","owner":"法务经理","currency":"CNY","amount":1000000,"startDate":"2026-01-01","endDate":"2026-12-31","autoRenew":true,"noticePeriodDays":30}
 """)).andExpect(status().isOk()).andExpect(jsonPath("$.data.businessVersion").value(1)).andReturn();long id=idOf(result);mvc.perform(post("/api/admin/contracts/{id}/activate",id).header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.state").value("ACTIVE"));mvc.perform(post("/api/admin/contracts/{id}/amendments",id).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":1,\"newAmount\":1200000,\"newEndDate\":\"2027-03-31\",\"autoRenew\":false,\"noticePeriodDays\":45,\"reason\":\"增加服务范围\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.businessVersion").value(2));var ob=mvc.perform(post("/api/admin/contracts/{id}/obligations",id).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"obligationNo\":\"OB-001\",\"title\":\"提交月度报告\",\"owner\":\"项目经理\",\"dueDate\":\"2026-09-10\"}")).andExpect(status().isOk()).andReturn();long oid=idOf(ob);mvc.perform(post("/api/admin/contracts/{id}/obligations/{oid}/complete",id,oid).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"evidence\":\"归档文件 reports/2026-08.pdf\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.state").value("COMPLETED"));mvc.perform(get("/api/admin/contracts/{id}",id).header("Authorization","Bearer "+token)).andExpect(status().isOk()).andExpect(jsonPath("$.data.amendments.length()").value(1)).andExpect(jsonPath("$.data.obligations.length()").value(1));}
 @Test void staleVersionIsRejected() throws Exception {var result=mvc.perform(post("/api/admin/contracts").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("""
 {"contractNo":"ENT-CLM-002","title":"测试合同","counterparty":"客户","organizationCode":"ZH-SH","owner":"法务","currency":"CNY","amount":10,"startDate":"2026-01-01","endDate":"2026-12-31","autoRenew":false,"noticePeriodDays":0}
 """)).andReturn();long id=idOf(result);mvc.perform(post("/api/admin/contracts/{id}/activate",id).header("Authorization","Bearer "+token));mvc.perform(post("/api/admin/contracts/{id}/amendments",id).header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"expectedVersion\":99,\"newAmount\":20,\"newEndDate\":\"2027-01-01\",\"autoRenew\":false,\"noticePeriodDays\":0,\"reason\":\"过期版本\"}")).andExpect(status().isBadRequest());}
 private long idOf(MvcResult result)throws Exception{var m=Pattern.compile("\\\"id\\\":(\\d+)").matcher(result.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}}
